# Generated by Django 5.1.2 on 2024-10-24 06:10
from django.contrib.auth.models import Group
from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Customer')
    Group.objects.get_or_create(name='Business')
    Group.objects.get_or_create(name='BackOffice')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
